import { VideoProject } from '../types';
import dogImage from '../assets/images/vintage_german_shepherd_etzel_1790500289989.jpg';
import jazzImage from '../assets/images/vintage_jazz_singer_stage_1790500311794.jpg';

export const PRESET_PROJECTS: VideoProject[] = [
  // 1. Viral Hollywood Mystery: Strongheart
  {
    id: 'preset-strongheart',
    title: 'Strongheart: Hollywood’s First Big Dog Star 🐕',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: dogImage,
    mediaName: 'vintage_german_shepherd_etzel.jpg',
    mediaType: 'image',
    script: {
      text: `Before Rin Tin Tin there was a German Shepherd called Etzel, trained as a police dog in Berlin during the First World War. You see, an American director bought him, renamed him Strongheart, and put him in a picture in nineteen twenty one. He was Hollywood's first big dog star. He has a star on the Walk of Fame. Studio lighting burns killed him.`,
      fontSize: 34,
      fontFamily: 'bebas-neue',
      fontWeight: '800',
      lineHeight: 1.45,
      textAlign: 'left',
      textColor: '#ffffff',
      boxBackgroundColor: '#000000',
      boxOpacity: 0.98,
      boxBorderRadius: 18,
      boxPadding: 26,
      boxMarginTop: 16,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#ef4444',
      highlightStyle: 'text',
      customKeywords: ['Strongheart', 'Walk of Fame'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 18,
      imageShadow: true,
      bgSource: 'auto',
      bgBlur: 38,
      bgDarkness: 0.35,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },

  // 2. High-Tension Historic Riot: Nat King Cole
  {
    id: 'preset-nat-king-cole',
    title: 'They Rushed The Stage While He Was Singing 🎹 - Nat King Cole',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: jazzImage,
    mediaName: 'vintage_jazz_singer_stage.jpg',
    mediaType: 'image',
    script: {
      text: `Birmingham, Alabama, April nineteen fifty six. Nat King Cole was three songs into a segregated show when men from a white supremacist group ran down the aisle and dragged him off his piano stool. Police found rifles in a car outside. He was hurt and couldn't finish, and he told the audience he had only come there to entertain them.`,
      fontSize: 33,
      fontFamily: 'impact',
      fontWeight: 'bold',
      lineHeight: 1.45,
      textAlign: 'left',
      textColor: '#ffffff',
      boxBackgroundColor: '#09090b',
      boxOpacity: 0.96,
      boxBorderRadius: 18,
      boxPadding: 26,
      boxMarginTop: 16,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#facc15',
      highlightStyle: 'pill',
      customKeywords: ['Nat King Cole', 'dragged him off'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 18,
      imageShadow: true,
      bgSource: 'auto',
      bgBlur: 40,
      bgDarkness: 0.4,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },

  // 3. Comedy & Bizarre History: The Great Emu War
  {
    id: 'preset-emu-war',
    title: 'The Great Emu War of 1932: When An Army Lost To Birds 🐦',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: dogImage,
    mediaName: 'australian_outback_emu.jpg',
    mediaType: 'image',
    script: {
      text: `In nineteen thirty two, the Australian military declared war on twenty thousand wild emus with heavy machine guns. But the giant birds split into guerrilla squads, dodged thousands of rounds, and outsmarted the soldiers in the desert. The army surrendered after ten days, making it the only war in history lost to birds.`,
      fontSize: 32,
      fontFamily: 'archivo-black',
      fontWeight: '900',
      textTransform: 'uppercase',
      lineHeight: 1.42,
      textAlign: 'center',
      textColor: '#ffffff',
      boxBackgroundColor: '#18181b',
      boxOpacity: 0.98,
      boxBorderRadius: 20,
      boxPadding: 24,
      boxMarginTop: 14,
      boxMaxWidth: 88,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#a3e635',
      highlightStyle: 'pill',
      customKeywords: ['declared war', 'lost to birds'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 16,
      imageShadow: true,
      bgSource: 'preset',
      bgPresetId: 'vintage-warmth',
      bgBlur: 35,
      bgDarkness: 0.45,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },

  // 4. Space Thriller: Apollo 11's 20-Second Death Clock
  {
    id: 'preset-apollo-11',
    title: 'Apollo 11’s 20-Second Death Clock: The Lunar Secret 🚀',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: jazzImage,
    mediaName: 'apollo_lunar_landing.jpg',
    mediaType: 'image',
    script: {
      text: `July nineteen sixty nine. Neil Armstrong had only twenty seconds of thruster fuel remaining before total engine flameout over the moon. Emergency alarm 1202 screamed in his headset as he manually steered past a deadly boulder crater. His heart rate soared to one hundred and fifty beats per minute before the dust settled.`,
      fontSize: 31,
      fontFamily: 'orbitron',
      fontWeight: 'bold',
      lineHeight: 1.46,
      textAlign: 'left',
      textColor: '#f8fafc',
      boxBackgroundColor: '#020617',
      boxOpacity: 0.97,
      boxBorderRadius: 14,
      boxPadding: 25,
      boxMarginTop: 16,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#06b6d4',
      highlightStyle: 'text',
      customKeywords: ['twenty seconds', 'engine flameout', 'alarm 1202'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 14,
      imageShadow: true,
      bgSource: 'preset',
      bgPresetId: 'cyber-blue',
      bgBlur: 40,
      bgDarkness: 0.5,
      bgScale: 1.4,
      motionType: 'ken-burns',
      motionIntensity: 0.04,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },

  // 5. Urban Legend & Catacombs Mystery: Paris Secret Cinema
  {
    id: 'preset-paris-catacombs',
    title: 'The Secret Underground Cinema of Paris (2004) 🎬',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: dogImage,
    mediaName: 'paris_catacombs_secret.jpg',
    mediaType: 'image',
    script: {
      text: `Deep beneath the Paris catacombs in two thousand four, police stumbled upon a hidden steel door. Inside, they found a fully wired subterranean cinema, restaurant bar, and surveillance cameras tracking their footsteps. When investigators returned the next morning, the entire facility had vanished without a trace, leaving only a note: Do not seek.`,
      fontSize: 32,
      fontFamily: 'merriweather',
      fontWeight: 'bold',
      lineHeight: 1.48,
      textAlign: 'left',
      textColor: '#f5f5f5',
      boxBackgroundColor: '#09090b',
      boxOpacity: 0.98,
      boxBorderRadius: 16,
      boxPadding: 26,
      boxMarginTop: 15,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#dc2626',
      highlightStyle: 'pill',
      customKeywords: ['subterranean cinema', 'vanished without a trace', 'Do not seek'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 18,
      imageShadow: true,
      bgSource: 'preset',
      bgPresetId: 'blood-red',
      bgBlur: 42,
      bgDarkness: 0.5,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },

  // 6. Royal Urdu Dastan: Koh-e-Noor Mystery (نستعلیق شاہی)
  {
    id: 'preset-urdu-kohenoor',
    title: 'شاہی داستان: کوہِ نور ہیرے کا پر اسرار راز 👑 (اردو)',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: jazzImage,
    mediaName: 'mughal_emperor_crown.jpg',
    mediaType: 'image',
    script: {
      text: `تاریخ کا سب سے بڑا سچ: کوہِ نور ہیرا جس بادشاہ کے پاس گیا، اس کی سلطنت اور خاندان چند برسوں میں برباد ہو گیا۔ مغل سلطنت سے لے کر نادر شاہ تک، خونریزی کا یہ سلسلہ چلتا رہا۔ کہتے ہیں کہ اس طلسماتی ہیرے پر ایک قدیم بددعا ہے جو صرف عورتوں پر اثر نہیں کرتی۔`,
      fontSize: 34,
      fontFamily: 'noto-nastaliq',
      fontWeight: 'bold',
      textDirection: 'rtl',
      lineHeight: 1.65,
      textAlign: 'right',
      textColor: '#ffffff',
      boxBackgroundColor: '#022c22',
      boxOpacity: 0.97,
      boxBorderRadius: 22,
      boxPadding: 26,
      boxMarginTop: 16,
      boxMaxWidth: 88,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: false,
      highlightMode: 'manual-only',
      highlightColor: '#facc15',
      highlightStyle: 'text',
      customKeywords: ['کوہِ نور ہیرا', 'قدیم بددعا'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 20,
      imageShadow: true,
      bgSource: 'preset',
      bgPresetId: 'emerald-luxury',
      bgBlur: 38,
      bgDarkness: 0.45,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },
];
