import { VideoProject } from '../types';

export const PRESET_PROJECTS: VideoProject[] = [
  {
    id: 'preset-strongheart',
    title: 'Strongheart: Hollywood’s First Big Dog Star 🐕',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: '/src/assets/images/vintage_german_shepherd_etzel_1790500289989.jpg',
    mediaName: 'vintage_german_shepherd_etzel.jpg',
    mediaType: 'image',
    script: {
      text: `Before Rin Tin Tin there was a German Shepherd called Etzel, trained as a police dog in Berlin during the First World War. You see, an American director bought him, renamed him Strongheart, and put him in a picture in nineteen twenty one. He was Hollywood's first big dog star. He has a star on the Walk of Fame. Studio lighting burns killed him.`,
      fontSize: 34,
      fontFamily: 'sans-serif',
      lineHeight: 1.45,
      textAlign: 'left',
      textColor: '#ffffff',
      boxBackgroundColor: '#000000',
      boxOpacity: 0.96,
      boxBorderRadius: 18,
      boxPadding: 26,
      boxMarginTop: 16,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: true,
      highlightMode: 'auto-and-manual',
      highlightColor: '#ef4444',
      highlightStyle: 'text',
      customKeywords: ['German Shepherd', 'First World War', 'Strongheart', 'Walk of Fame', 'killed'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 18,
      imageShadow: true,
      bgSource: 'auto',
      bgBlur: 38,
      bgDarkness: 0.35,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },
  {
    id: 'preset-nat-king-cole',
    title: 'They Rushed The Stage While He Was Singing 🎹 - Nat King Cole',
    durationSeconds: 8,
    fps: 30,
    resolution: '1080p',
    mediaUrl: '/src/assets/images/vintage_jazz_singer_stage_1790500311794.jpg',
    mediaName: 'vintage_jazz_singer_stage.jpg',
    mediaType: 'image',
    script: {
      text: `Birmingham, Alabama, April nineteen fifty six. Nat King Cole was three songs into a segregated show when men from a white supremacist group ran down the aisle and dragged him off his piano stool. Police found rifles in a car outside. He was hurt and couldn't finish, and he told the audience he had only come there to entertain them.`,
      fontSize: 33,
      fontFamily: 'sans-serif',
      lineHeight: 1.45,
      textAlign: 'left',
      textColor: '#ffffff',
      boxBackgroundColor: '#000000',
      boxOpacity: 0.96,
      boxBorderRadius: 18,
      boxPadding: 26,
      boxMarginTop: 16,
      boxMaxWidth: 86,
      moveX: 0,
      moveY: 0,
      autoHighlightKeywords: true,
      highlightMode: 'auto-and-manual',
      highlightColor: '#ef4444',
      highlightStyle: 'text',
      customKeywords: ['Nat King Cole', 'segregated', 'white supremacist', 'rifles', 'hurt'],
    },
    adjust: {
      scale: 1.0,
      moveX: 0,
      moveY: 0,
      imageBorderRadius: 18,
      imageShadow: true,
      bgSource: 'auto',
      bgBlur: 40,
      bgDarkness: 0.4,
      bgScale: 1.4,
      motionType: 'static',
      motionIntensity: 0.03,
    },
    audio: {
      enabled: false,
      ambientTrack: 'none',
      volume: 0.7,
    },
  },
];
